sudo: required
services:
  - docker

before_install:
  - docker build -t rrdunn11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rrdunn11/react-test npm test

after_success:
  - docker build -t rrdunn11/multi-client ./client
  - docker build -t rrdunn11/multi-nginx ./nginx
  - docker build -t rrdunn11/multi-server ./server
  - docker build -t rrdunn11/multi-worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push rrdunn11/multi-client
  - docker push rrdunn11/multi-nginx
  - docker push rrdunn11/multi-server
  - docker push rrdunn11/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-895245846823
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY